s3 access fix
AllenCell/EMT_image_analysis pull request #20
Opened 2024-08-30 22:24 UTC by mfs4rd

correcting to use columns with `https://` paths instead of `s3:`

2024-09-03 17:28 UTC, pgarrison commented
How did you test this?

2024-09-06 16:13 UTC, mfs4rd commented
@pgarrison the change was necessary to make similar code in EMT_data_analysis work so I'm applying it here as well.

2024-09-06 20:38 UTC, pgarrison commented
@mfs4rd that makes sense. But we should still validate somehow that the new code works as expected.

2024-09-18 20:25 UTC, mfs4rd commented
@pgarrison Should have mentioned that I tested this code in `EMT_data_analysis` so unless the path it's given is incorrect it should work the same here

2025-04-10 16:07 UTC, mfs4rd commented
@smishra3 @vianamp Please review this PR for adding to the release branch

2025-04-10 16:23 UTC, smishra3 requested changes
Function parameter need to be addressed for the function process_seg (seg in line 62 vs segmentation in line 77).

2025-04-11 16:06 UTC, mfs4rd commented
> Function parameter need to be addressed for the function process_seg (seg in line 62 vs segmentation in line 77).

This was changed locally but the commit didn't push correctly for some reason. Fixed now

2025-04-11 17:14 UTC, smishra3 approved these changes
successfully reproduced the results

2025-04-12 00:13 UTC, vianamp approved these changes
Looks good but did not try to run it.

2025-04-12 03:22 UTC, merged